name: CI
on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v3
        env:
          VERSION: ${{ github.ref }}
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 2  # to be able to obtain files changed in the latest commit

      - name: Generate Tag
        id: generate_tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          DRY_RUN: true

      - name: Check out nordmart-infra-gitops-config repo
        id: checkout-ci
        uses: actions/checkout@v3
        with:
          repository: stakater/nordmart-infra-gitops-config
          path: 'nordmart-infra-gitops-config'
          token: ${{ secrets.STAKATER_GITHUB_TOKEN }}
      - run: |
          mv nordmart-infra-gitops-config /home/runner/work/nordmart-infra-gitops-config

      - name: Update Workshop Version
        env:
          VERSION: ${{ steps.generate_tag.outputs.tag }}
        run: |
          cd /home/runner/work/nordmart-infra-gitops-config
          sed -i "s/targetRevision:.*/targetRevision: ${VERSION}/" dev-test/argocd-apps/workshop-exercise.yaml

      - name: Commit files
        run: |
          cd /home/runner/work/nordmart-infra-gitops-config
          diff="$(git diff)"
          echo '::echo::on'
          echo "$diff"
          echo '::echo::off'
          git config --local user.email "stakater@gmail.com"
          git config --local user.name "stakater-user"
          git status 
          git add dev-test/argocd-apps/workshop-exercise.yaml
          git commit -m "[skip-ci] Update workshop exercise" -a

      # Push workshop-exercise.yaml with Updated Version
      - name: Push changes
        shell: bash {0}
        run: |
          cd /home/runner/work/nordmart-infra-gitops-config
          git config --local user.email "stakater@gmail.com"
          git config --local user.name "stakater-user"
          git remote set-url origin https://x-access-token:${{ secrets.STAKATER_GITHUB_TOKEN }}@github.com/stakater/nordmart-infra-gitops-config
          git push origin
          if [ $? -eq 0 ]; then
              echo OK Pushed Succesfully.
          else
            for i in 1 2 3
            do
              echo "Trying Push Again Attempt:" $i
              git pull --rebase --strategy-option theirs
              if [ $? -eq 0 ]; then
                  echo OK Pulled
              else
                  continue
              fi
              git push origin
              if [ $? -eq 0 ]; then
                  echo OK Pushed
                  break
              else
                  if [ $i -eq 3 ];then
                  echo "Fail: Couldnt Push to Remote"
                  exit 1
                  fi
                  continue
              fi
            done
          fi
